bot:
  token: 332gdgrdgdsgsdfg3
  chatId: 2141241241
spring:
  application:
    name: SarComp
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sarcomp}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  servlet:
    multipart:
      max-file-size: 10MB  # Максимальный размер загружаемого файла
      max-request-size: 10MB  # Максимальный размер всего запроса
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
jwt:
  access:
    secret: pCUDF0J7Z/bKD8wysWJIzys5AabF4Ug2P7t3sk7aSkIi4Z1sUpFFFSTha4tbr/Kt5E6rLabIwCR1xQVmALsiRA==
    exp_time: 3000000
  refresh:
    secret: pCUDF0J7Z/bKD8wysWJIzys5AabF4Uy2P7t3sk7aSkIi4Z1sUpFFFSTha4tbr/Kt5E6rLabIwCR1xQVmALsiRA==
    exp_time: 3000000
kafka:
  topic:
    name: my-topic
    group: my-group
server:
  port: 8080
